version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=secretkey123
      - DATABASE_URL=postgresql+asyncpg://user:password@db/dbname
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: